name: discord_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.9
dependencies: 
  nyxx: ^2.0.0-rc.7
  nyxx_commander: ^2.0.0-rc.10
  nyxx_extensions: ^2.0.0-rc.7
  nyxx_interactions: ^2.0.0-rc.8
